@extends('admin.layout.layout')
@push('styles') <style> .dashboard-page { background-color: #f8fafc; min-height: calc(100vh - 57px); }
 .metric-card { background: #ffffff; border: 1px solid #e2e8f0; border-radius: 1rem; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03); display: flex; flex-direction: column; height: 100%; min-height: 130px; overflow: hidden; position: relative; transition: transform 0.2s ease, box-shadow 0.2s ease; }
 .metric-card:hover { transform: translateY(-4px); box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -2px rgba(0, 0, 0, 0.04); border-color: #cbd5e1; }
 .metric-card.primary { border-left: 4px solid #3b82f6; } .metric-card.success { border-left: 4px solid #10b981; } .metric-card.warning { border-left: 4px solid #f59e0b; } .metric-card.danger { border-left: 4px solid #ef4444; }
 .metric-card-body { padding: 1.5rem; display: flex; flex-direction: column; justify-content: center; height: 100%; }
 .metric-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 1rem; }
 .metric-label { color: #64748b; font-size: 0.875rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; margin: 0; }
 .metric-icon { width: 40px; height: 40px; border-radius: 0.75rem; display: flex; align-items: center; justify-content: center; font-size: 1.25rem; }
 .metric-icon.primary { background: #eff6ff; color: #3b82f6; } .metric-icon.success { background: #ecfdf5; color: #10b981; } .metric-icon.warning { background: #fffbeb; color: #f59e0b; } .metric-icon.danger { background: #fef2f2; color: #ef4444; }
 .metric-value { color: #0f172a; font-size: 1.875rem; font-weight: 700; line-height: 1.2; margin: 0; } .metric-subvalue { font-size: 0.875rem; font-weight: 500; margin-top: 0.5rem; display: inline-block; padding: 0.25rem 0.5rem; border-radius: 0.375rem; }
 .section-title { font-size: 1.125rem; font-weight: 700; color: #1e293b; margin-bottom: 1.25rem; display: flex; align-items: center; gap: 0.5rem; }
 .dashboard-card { background: #ffffff; border: 1px solid #e2e8f0; border-radius: 1rem; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05); overflow: hidden; height: 100%; transition: box-shadow 0.2s ease; }
 .dashboard-card:hover { box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.08); }
 .dashboard-card .card-header { background: #ffffff; border-bottom: 1px solid #f1f5f9; padding: 1.25rem 1.5rem; font-weight: 700; font-size: 1rem; color: #0f172a; display: flex; align-items: center; justify-content: space-between; }
 .dashboard-card .card-body { padding: 1.5rem; }
 .state-row { display: flex; justify-content: space-between; align-items: center; padding: 0.75rem 0; color: #475569; font-weight: 500; font-size: 0.95rem; border-bottom: 1px solid #f1f5f9; }
 .state-row:last-child { border-bottom: none; padding-bottom: 0; } .state-row:first-child { padding-top: 0; }
 .dashboard-table-container { background: #ffffff; border: 1px solid #e2e8f0; border-radius: 1rem; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05); overflow: hidden; margin-top: 1.5rem; }
 .dashboard-table { width: 100%; margin-bottom: 0; }
 .dashboard-table thead th { background: #f8fafc; border-bottom: 1px solid #e2e8f0; color: #64748b; font-size: 0.75rem; letter-spacing: 0.05em; padding: 1rem 1.5rem; text-transform: uppercase; font-weight: 700; }
 .dashboard-table tbody td { border-bottom: 1px solid #f1f5f9; color: #334155; padding: 1rem 1.5rem; vertical-align: middle; font-weight: 500; }
 .dashboard-table tbody tr:hover { background: #f8fafc; }
 .employee-name { color: #0f172a; font-weight: 600; font-size: 0.95rem; }
 .btn-action { font-weight: 600; font-size: 0.8125rem; padding: 0.4rem 0.875rem; border-radius: 0.5rem; transition: all 0.2s; display: inline-flex; align-items: center; gap: 0.375rem; }
 .btn-action-map { background: #eff6ff; color: #2563eb; border: 1px solid #bfdbfe; } .btn-action-map:hover { background: #dbeafe; color: #1d4ed8; }
 .btn-action-log { background: #fdf2f8; color: #db2777; border: 1px solid #fbcfe8; } .btn-action-log:hover { background: #fce7f3; color: #be185d; }
 </style>@endpush
@section('content') <main class="app-main dashboard-page">

 <div class="content py-4"> <div class="container-fluid"> <h5 class="section-title"><i class="fas fa-chart-line text-primary"></i> Daily Overview</h5> <!-- Top Cards Row --> <div class="row g-4 mb-4"> <div class="col-lg-3 col-md-6"> <a href="{{ url('admin/trips') }}" class="text-decoration-none d-block h-100"> <div class="metric-card primary"> <div class="metric-card-body"> <div class="metric-header"> <h6 class="metric-label">All Active Trips</h6> <div class="metric-icon primary"><i class="fas fa-truck"></i></div> </div> <h3 class="metric-value">{{ $todaysActiveTripCount }}</h3> </div> </div> </a> </div> <div class="col-lg-3 col-md-6"> <a href="{{ url('admin/order') }}" class="text-decoration-none d-block h-100"> <div class="metric-card success"> <div class="metric-card-body"> <div class="metric-header"> <h6 class="metric-label">Today's Orders</h6> <div class="metric-icon success"><i class="fas fa-shopping-cart"></i></div> </div> <h3 class="metric-value">{{ $todaysOrderCount }}</h3> <span class="metric-subvalue bg-success bg-opacity-10 text-success">₹{{ number_format($todaysOrderValue, 2) }}</span> </div> </div> </a> </div> <div class="col-lg-3 col-md-6"> <a href="{{ route('party-payment') }}" class="text-decoration-none d-block h-100"> <div class="metric-card warning"> <div class="metric-card-body"> <div class="metric-header"> <h6 class="metric-label">Payment Collection</h6> <div class="metric-icon warning"><i class="fas fa-rupee-sign"></i></div> </div> <h3 class="metric-value">₹{{ number_format($todaysPaymentCollection, 2) }}</h3> </div> </div> </a> </div> <div class="col-lg-3 col-md-6"> <a href="{{ url('admin/party') }}" class="text-decoration-none d-block h-100"> <div class="metric-card danger"> <div class="metric-card-body"> <div class="metric-header"> <h6 class="metric-label">Party Visits</h6> <div class="metric-icon danger"><i class="fas fa-users"></i></div> </div> <h3 class="metric-value">{{ $todaysPartyVisits }}</h3> </div> </div> </a> </div> </div>
 <h5 class="section-title mt-2"><i class="fas fa-sync-alt text-primary"></i> Tally Integration</h5> <!-- Tally Integration Overview Row --> <div class="row g-4 mb-4"> <div class="col-lg-4 col-md-6"> <a href="{{ route('sales.bill.register') }}" class="text-decoration-none d-block h-100"> <div class="metric-card success"> <div class="metric-card-body"> <div class="metric-header"> <h6 class="metric-label">Total Debit (Bill)</h6> <div class="metric-icon success"><i class="fas fa-file-invoice-dollar"></i></div> </div> <h3 class="metric-value">₹{{ number_format($tallyTotalSalesAmount, 2) }}</h3> </div> </div> </a> </div> <div class="col-lg-4 col-md-6"> <a href="{{ route('party.opening.closing') }}" class="text-decoration-none d-block h-100"> <div class="metric-card warning"> <div class="metric-card-body"> <div class="metric-header"> <h6 class="metric-label">Closing Balance</h6> <div class="metric-icon warning"><i class="fas fa-balance-scale"></i></div> </div> <h3 class="metric-value">₹{{ number_format(abs($tallyTotalClosingBalance), 2) }}</h3> </div> </div> </a> </div> <div class="col-lg-4 col-md-6"> <a href="{{ route('partywise.payment.credit') }}" class="text-decoration-none d-block h-100"> <div class="metric-card danger"> <div class="metric-card-body"> <div class="metric-header"> <h6 class="metric-label">Total Payment Credit</h6> <div class="metric-icon danger"><i class="fas fa-credit-card"></i></div> </div> <h3 class="metric-value">₹{{ number_format($tallyTotalCreditAmount, 2) }}</h3> </div> </div> </a> </div> </div>
 <h5 class="section-title mt-2"><i class="fas fa-map-marked-alt text-primary"></i> State-wise Metrics</h5> <!-- Middle Cards Row --> <div class="row g-4 mb-4"> <!-- Target Vs Ach % --> <div class="col-lg-3 col-md-6"> <div class="dashboard-card"> <div class="card-header"> <a href="{{ route('budget.report') }}" class="text-decoration-none text-dark d-flex justify-content-between align-items-center w-100"> <span>Target Vs Ach %</span> <i class="bi bi-arrow-right-short fs-5 text-muted"></i> </a> </div> <div class="card-body"> @forelse($statesData as $state) <div class="state-row"> <span>{{ $state->name }}</span> <div class="text-end"> <span class="text-slate-400 small me-2" title="Achievement: {{ number_format($state->achievement, 0) }}"> ₹{{ number_format($state->target, 0) }} </span> <span class="text-primary fw-bold">{{ $state->target_ach }}%</span> </div> </div> @empty <div class="text-center text-muted py-3">No state data</div> @endforelse </div> </div> </div>
 <!-- Partywise Outstanding --> <div class="col-lg-3 col-md-6"> <div class="dashboard-card"> <div class="card-header"> <a href="{{ route('party.opening.closing') }}" class="text-decoration-none text-dark d-flex justify-content-between align-items-center w-100"> <span>Party Outstanding</span> <i class="bi bi-arrow-right-short fs-5 text-muted"></i> </a> </div> <div class="card-body"> @forelse($statesData as $state) <div class="state-row"> <span>{{ $state->name }}</span> <span class="text-danger fw-semibold">₹{{ number_format($state->outstanding, 0) }}</span> </div> @empty <div class="text-center text-muted py-3">No state data</div> @endforelse </div> </div> </div>
 <!-- TA-DA Info --> <div class="col-lg-3 col-md-6"> <div class="dashboard-card"> <div class="card-header"> <a href="{{ url('admin/expense') }}" class="text-decoration-none text-dark d-flex justify-content-between align-items-center w-100"> <span>TA-DA Info</span> <i class="bi bi-arrow-right-short fs-5 text-muted"></i> </a> </div> <div class="card-body"> @forelse($statesData as $state) <div class="state-row"> <span>{{ $state->name }}</span> <span class="text-warning fw-semibold">₹{{ number_format($state->tada, 0) }}</span> </div> @empty <div class="text-center text-muted py-3">No state data</div> @endforelse </div> </div> </div>
 <!-- Payment Credit --> <div class="col-lg-3 col-md-6"> <div class="dashboard-card"> <div class="card-header"> <a href="{{ route('party-payment') }}" class="text-decoration-none text-dark d-flex justify-content-between align-items-center w-100"> <span>Payment Credit</span> <i class="bi bi-arrow-right-short fs-5 text-muted"></i> </a> </div> <div class="card-body"> @forelse($statesData as $state) <div class="state-row"> <span>{{ $state->name }}</span> <span class="text-success fw-semibold">₹{{ number_format($state->payment_credit, 0) }}</span> </div> @empty <div class="text-center text-muted py-3">No state data</div> @endforelse </div> </div> </div> </div>
 <!-- Bottom Table --> <div class="dashboard-table-container table-responsive"> <table class="table dashboard-table text-nowrap"> <thead> <tr> <th>Employee Name</th> <th>Day Start Time / Day End Time</th> <th>Login Hrs</th> <th>Tour Plan / Places</th> <th>Actions</th> </tr> </thead> <tbody> @forelse($employeeData as $employee) <tr> <td> <span class="employee-name">{{ $employee->name }}</span> </td> <td> <div class="text-success fw-bold">{{ $employee->day_start }}</div> <div class="text-danger fw-bold">{{ $employee->day_end }}</div> </td> <td><span class="badge bg-light text-dark border">{{ $employee->login_hrs }}</span></td> <td> <div class="fw-semibold text-primary mb-1"><i class="fas fa-route me-1"></i>{{ $employee->tour_plan }}</div> @forelse ($employee->places_visited as $customer) <span class="badge bg-light text-dark border mt-1"> <i class="fas fa-user me-1"></i>{{ $customer->agro_name ?? '-'}} </span><br> @empty @endforelse </td> <td> <div class="d-flex gap-2"> @if($employee->trip_id) <a href="{{ route('trips.show', $employee->trip_id) }}" class="btn-action btn-action-map text-decoration-none" target="_blank"> <i class="fas fa-map-marked-alt me-1"></i> MAP </a> <button type="button" class="btn-action btn-action-log text-decoration-none border-0" onclick="loadTripLogs({{ $employee->trip_id }}, '{{ route('trips.logs', $employee->trip_id) }}')"> <i class="fas fa-list me-1"></i> LOGS </button> @else <span class="btn-action btn-action-map text-decoration-none opacity-50"><i class="fas fa-map-marked-alt me-1"></i> MAP</span> <span class="btn-action btn-action-log text-decoration-none opacity-50"><i class="fas fa-list me-1"></i> LOGS</span> @endif </div> </td> </tr> @empty <tr> <td colspan="5" class="text-center py-4 text-muted">No active employees found today.</td> </tr> @endforelse </tbody> </table> </div>
 {{-- Session History Modal --}} <div class="modal fade" id="sessionHistoryModal" tabindex="-1" aria-hidden="true"> <div class="modal-dialog modal-lg modal-dialog-scrollable"> <div class="modal-content"> <div class="modal-header bg-primary text-white"> <h5 class="modal-title" id="sessionHistoryModalLabel">Trip Logs</h5> <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button> </div> <div class="modal-body"> <div id="sessionHistoryContent">Loading...</div> </div> </div> </div> </div>
 </div> </div> </main>@endsection
@push('scripts')<script> function loadTripLogs(tripId, url) { var modalElement = document.getElementById('sessionHistoryModal'); // Rename modal title document.getElementById('sessionHistoryModalLabel').innerText = 'Trip Logs #' + tripId; // Ensure bootstrap modal is loaded, if not, use jQuery depending on app's standard if (typeof bootstrap !== 'undefined') { var modal = new bootstrap.Modal(modalElement); modal.show(); } else { $(modalElement).modal('show'); }
 document.getElementById('sessionHistoryContent').innerHTML = ` <div class="text-center py-4"> <div class="spinner-border text-primary"></div> </div>`; fetch(url, { headers: { 'Accept': 'application/json' } }) .then(response => response.json()) .then(res => { let logs = res.logs ?? []; if (logs.length === 0) { document.getElementById('sessionHistoryContent').innerHTML = '<p class="text-center text-muted">No logs available</p>'; return; }
 let tableHtml = ` <div class="table-responsive"> <table class="table table-bordered table-striped table-sm align-middle text-nowrap"> <thead class="table-light"> <tr> <th>#</th> <th>Latitude</th> <th>Longitude</th> <th>Battery</th> <th>GPS</th> <th>Mobile Status</th> <th>Recorded At</th> </tr> </thead> <tbody> `;
 logs.forEach((log, index) => { let gpsStatus = log.gps_status == 1 ? '<span class="badge bg-success">On</span>' : '<span class="badge bg-danger">Off</span>'; let mobileStatus = log.mobile_status == 1 ? '<span class="badge bg-success">On</span>' : '<span class="badge bg-danger">-</span>'; tableHtml += ` <tr> <td>${index + 1}</td> <td>${log.latitude}</td> <td>${log.longitude}</td> <td>${log.battery}</td> <td>${gpsStatus}</td> <td>${mobileStatus}</td> <td>${log.recorded_at}</td> </tr> `; });
 tableHtml += `</tbody></table></div>`; document.getElementById('sessionHistoryContent').innerHTML = tableHtml; }) .catch(error => { console.error("Error loading trip logs:", error); document.getElementById('sessionHistoryContent').innerHTML = '<p class="text-danger">Failed to load trip logs.</p>'; }); }</script>@endpush
